"""Embed the JSON data into JS files so the site also works when index.html is opened
directly from disk (file://), where browsers block fetch() of local JSON.

Run after changing anything in data/ or assets/img/manifest.json:
    python scripts/bundle_data.py
Writes js/data.js (products, journal, quiz, image manifest) and js/slides-data.js (hero slides).
"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def load(rel):
    return json.load(open(os.path.join(ROOT, rel), encoding='utf-8'))

def write(path, payload):
    js = '/* generated by scripts/bundle_data.py — do not edit */\nwindow.MV_DATA = Object.assign(window.MV_DATA || {}, ' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')) + ');\n'
    open(os.path.join(ROOT, path), 'w', encoding='utf-8').write(js)
    print(path, round(len(js.encode('utf-8')) / 1024), 'KB')

write('js/data.js', {k: load(k) for k in ['data/products.json', 'data/journal.json', 'data/quiz.json', 'assets/img/manifest.json']})

# Image masks (bottle silhouettes for the cast shadows) as small inline PNGs:
# CSS mask-image with a file URL is blocked on file://, a data: URI is not.
import base64, io
from PIL import Image
slides = load('data/slides.json')
names = set()
def walk(n):
    if n.get('mask'):
        for f in n.get('f', []) if isinstance(n.get('f'), list) else []:
            if 'i' in f: names.add(f['i'])
    if isinstance(n.get('c'), list):
        for c in n['c']: walk(c)
for s in slides['slides']:
    for bp in ('desktop', 'mobile'):
        for l in s[bp]['layers']: walk(l)
man = load('assets/img/manifest.json')
masks = {}
for nm in sorted(names):
    files = man[nm]['files']; src = files[max(files, key=int)]
    im = Image.open(os.path.join(ROOT, src)).convert('RGBA')
    a = im.getchannel('A'); a.thumbnail((240, 240))
    out = Image.new('LA', a.size, 0); out.putalpha(a)
    buf = io.BytesIO(); out.save(buf, 'PNG', optimize=True)
    masks[nm] = 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()
write('js/slides-data.js', {'data/slides.json': slides, 'masks': masks})
